export default {
  testEnvironment: "node",
  transform: {},
  setupFiles: ["<rootDir>/tests/setup.js"],
  globalTeardown: "<rootDir>/tests/helpers/prisma-db-setup.js",
  moduleFileExtensions: ["js"],
  testMatch: ["**/tests/**/*.test.js", "**/?(*.)+(spec|test).js"],
  collectCoverageFrom: [
    "src/**/*.js",
    "!src/server.js",
    "!src/generated/**",
    "!**/node_modules/**",
  ],
  coverageDirectory: "coverage",
  verbose: false,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
